sudo: required
service: 
 - docker

before_install: 
  - docker build -t jasonchong/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true jasonchong/react-test npm test

after_success:
  - docker build -t jasonchong/multi-client ./client
  - docker build -t jasonchong/multi-nginx ./nginx
  - docker build -t jasonchong/multi-server ./server
  - docker build -t jasonchong/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push stephengrider/multi-client
  - docker push stephengrider/multi-nginx
  - docker push stephengrider/multi-server
  - docker push stephengrider/multi-worker
