sudo: required
service: 
 - docker

 before_install: 
  - docker build -t jasonchong/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run jasonchong/react-test npm test -- --coverage

after_success:
  - docker build -t jasonchong/multi-client ./client
  - docker build -t jasonchong/multi-nginx ./nginx
  - docker build -t jasonchong/multi-server ./server
  - docker build -t jasonchong/multi-worker ./worker